import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const dmSans = DM_Sans({
	subsets: ['latin'],
});

const ocra = localFont({
	src: './OCRAStd.otf',
	variable: '--font-ocra',
});

export const metadata: Metadata = {
	title: 'Global Impact',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${dmSans.className} ${ocra.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
